name: Grafana Installation testing by raja gaur

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  grafana-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common wget apt-transport-https

    - name: Add Grafana Repository
      run: |
        sudo mkdir -p /etc/apt/keyrings
        sudo wget -q -O /etc/apt/keyrings/grafana.key https://packages.grafana.com/gpg.key
        echo "deb [signed-by=/etc/apt/keyrings/grafana.key] https://packages.grafana.com/oss/deb stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

    - name: Update Package Lists & Install Grafana
      run: |
        sudo apt-get update
        sudo apt-get install -y grafana

    - name: Enable & Start Grafana Service
      run: |
        sudo systemctl enable grafana-server
        sudo systemctl start grafana-server

    - name: Verify Grafana Installation
      run: |
        sudo systemctl status grafana-server --no-pager
